version: '2'
services:
  # zookeeper image
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # kafka image
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # prometheus image
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - "9090:9090"
    volumes:
      - "/Users/kimjongchan/study/kafka-basic/prometheus.yml:/etc/prometheus/prometheus.yml"

  # grafana image
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "80:3000"

  # node-exporter image
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"