scrape_configs:
#  - job_name: 'order-api-server'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['host.docker.internal:8080']
  - job_name: 'prometheus' # 잡 이름
    static_configs:
    - targets: [ 'localhost:9090' ]
    scrape_interval: 1s

  - job_name: 'order-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
    scrape_interval: 1s
  - job_name: 'payment-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
    scrape_interval: 1s

  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]
    scrape_interval: 1s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'host.docker.internal:9187' ]
    scrape_interval: 1s


